### ISSUE TITLE
Add delegate for more powerful use case handling

### ISSUE THREAD

**Issue by joshholat** [nullscreen/bark#16]
From my email to you...

Just had a potentially neat idea for BARK. Would it be possible to give BARK some sort of delegate in the app? Here's what I'm thinking.

At StageBloc, it'd be nice if @tomgiles, you and I could use BARK in the production app, but only because we meet a certain criteria (i.e. we're employees at SB). So open shake of the app, you could do something like (pseudo code):

```
app is shaken...
    if delegate responses to selector (:checkForCertainCriteria) and :checkForCertainCriteria returns YES
        show BARK
```

Then in our app's delegate, we'd just define that function and put whatever logic we want inside of it.

**Comment by austinlouden** [comment]
https://github.com/stagebloc/bark#using-bark-in-production
