### ISSUE TITLE
What should I do about this?

### ISSUE THREAD

**Issue by emichaud** [nullscreen/bark#25]
Issue:
When I tap this button
Expected Behavior : odd stuff happens

iOS Version: 6.1
Model: iPhone Simulator
App Version: 1.0
Build: 1.0
![screenshot](%28null%29)

**Comment by emichaud** [comment]
sweet - just testing! thank you

**Comment by joshholat** [comment]
@emichaud May I ask how you got that blank / null image in there?

**Comment by austinlouden** [comment]
That's happening because the ImageShack API key isn't set. Let me add that to the README

**Comment by joshholat** [comment]
Make sure it alerts the user of that as well if they try to with no key. 

Josh Holat
Cofounder at StageBloc
